global using Ardalis.Result;
global using Ardalis.Specification;
global using FamilyTaskManager.Core.FamilyAggregate;
global using FamilyTaskManager.Core.SpotAggregate;
global using FamilyTaskManager.Core.TaskAggregate;
global using FamilyTaskManager.Core.UserAggregate;
global using FamilyTaskManager.UseCases.Families.Specifications;
global using FamilyTaskManager.UseCases.Spots.Specifications;
global using FamilyTaskManager.UseCases.Tasks.Specifications;
global using FamilyTaskManager.UseCases.Users.Specifications;
global using Mediator;
global using TaskStatus = FamilyTaskManager.Core.TaskAggregate.TaskStatus;
global using FamilyTaskManager.Core.Interfaces;
global using FamilyTaskManager.Core.Specifications;
